-- queries all content generated by all users
select	distinct lastmodifier as user_key
,		body
from	content c
join	bodycontent bc on bc.contentid = c.contentid
where	contenttype in ('PAGE', 'COMMENT')
and		lastmodifier is not null
and		c.content_status != 'deleted'
and		body != ''
order by lastmodifier
;